on:
  push:
    branches:
      - main
      - portfolio
  pull_request:
      branches:
        [main, portfolio]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login to Dockerhub
        run: docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}

      - name: Build docker image
        run: |
          ls -la
          docker build -t Jude-cicd .
