"""added like and comments feature

Revision ID: cf803dce6c74
Revises: b0bc9d5e5271
Create Date: 2025-02-28 17:24:01.098689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf803dce6c74'
down_revision: Union[str, None] = 'b0bc9d5e5271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
